version: '3.8'
services:
  frontend:
    container_name: gobdocs-frontend
    build: 
      context: .
      args:
        - VITE_REACT_APP_BACKEND=https://gobdocs-backend.up.railway.app
    ports:
      - "5173:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    platform: linux/arm64